package net.boardrank.boardgame.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import net.boardrank.global.config.AWSConfig;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "br_matchStatus")
public class AccountMatchStatus {

    public AccountMatchStatus(Long accountId, Long gameMatchId, Long boardgameId, String attribute, String value) {
        this.createdAt = LocalDateTime.now();
        this.accountId = accountId;
        this.gameMatchId = gameMatchId;
        this.boardgameId = boardgameId;
        this.attribute = attribute;
        this.value = value;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "accountId-createdAt-index")
    private Long accountId;

    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "accountId-createdAt-index")
    @DynamoDBTypeConverted(converter = AWSConfig.LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    private Long gameMatchId;

    @DynamoDBAttribute
    private Long boardgameId;

    @DynamoDBAttribute
    private String attribute;

    @DynamoDBAttribute
    private String value;

}
