package net.boardrank.boardgame.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import net.boardrank.global.config.DynamoDBConfig;

import java.time.LocalDateTime;

@Getter
@Setter // Setters are used in aws-dynamodb-sdk
@NoArgsConstructor
@DynamoDBTable(tableName = "br_comment")
public class Comment {

    public Comment(Long gameMatchId, Long accountId, String accountName, String content) {
        this.gameMatchId = gameMatchId;
        this.accountId = accountId;
        this.accountName = accountName;
        this.content = content;
        this.createdAt = LocalDateTime.now();
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "gameMatchId-createdAt-index")
    private Long gameMatchId;

    @DynamoDBAttribute
    private Long accountId;

    @DynamoDBAttribute
    private String accountName;

    @DynamoDBAttribute
    private String content;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    private boolean deleted;


    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "gameMatchId-createdAt-index")
    @DynamoDBTypeConverted(converter = DynamoDBConfig.LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBConfig.LocalDateTimeConverter.class)
    private LocalDateTime deletedAt;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBConfig.LocalDateTimeConverter.class)
    private LocalDateTime lastModifiedAt;

}
